--liquibase formatted sql
--changeset eimert:1.0-001-salaries splitStatements:true endDelimiter:;

DROP TABLE IF EXISTS SALARIES;

CREATE TABLE IF NOT EXISTS SALARIES (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name TEXT NOT NULL,
  position TEXT NOT NULL,
  department TEXT NOT NULL,
  salary DOUBLE);

INSERT INTO SALARIES VALUES(NULL, 'AARON,  ELVIA J','WATER RATE TAKER','WATER MGMNT',88968.00);
COMMIT;
